/**
 * History Analytics Entity
 * Stores events when tutors open and use the History View feature
 * Used for BQ16: Weekly percentage of tutors using history view
 */
export class HistoryAnalytics {
  /**
   * Document ID (auto-generated by Firestore)
   */
  id?: string;

  /**
   * Tutor's unique identifier (Firebase UID)
   */
  tutorId: string;

  /**
   * Type of history view event
   * e.g., "history_view_opened", "history_filtered", etc.
   */
  eventType: string;

  /**
   * Timestamp when the event occurred (from client)
   * ISO 8601 format: "2026-05-26T18:30:00Z"
   */
  timestamp: Date;

  /**
   * Server timestamp when the event was recorded
   * Automatically set by Firebase
   */
  createdAt?: Date;

  /**
   * Optional metadata about the event
   * Can store additional context like filters applied, view duration, etc.
   */
  metadata?: Record<string, any>;
}
