/**
 * Occupancy Entity
 * Stores pre-calculated occupancy metrics for tutor-subject combinations
 * Updated whenever sessions or availabilities are created/updated
 */
export class Occupancy {
  /**
   * Document ID (auto-generated by Firestore)
   */
  id?: string;

  /**
   * Tutor's unique identifier (Firebase UID)
   */
  tutorId: string;

  /**
   * Subject/Course ID
   */
  subjectId: string;

  /**
   * Subject/Course name
   */
  subjectName: string;

  /**
   * Total available hours for this tutor-subject combination
   * in the last 2 years
   */
  totalAvailableHours: number;

  /**
   * Total session hours for this tutor-subject combination
   * in the last 2 years (only COMPLETED sessions)
   */
  totalSessionHours: number;

  /**
   * Total number of sessions
   */
  totalSessions: number;

  /**
   * Calculated occupancy rate (0-100)
   */
  occupancyRate: number;

  /**
   * Sessions per hour ratio
   */
  sessionsPerHour: number;

  /**
   * Number of sessions in high-demand periods
   */
  highDemandSessions: number;

  /**
   * Hours of sessions in high-demand periods
   */
  highDemandSessionHours: number;

  /**
   * Occupancy rate during high-demand periods (0-100)
   */
  highDemandOccupancyRate: number;

  /**
   * Sessions per hour during high-demand periods
   */
  highDemandSessionsPerHour: number;

  /**
   * Number of sessions in normal demand periods
   */
  normalDemandSessions: number;

  /**
   * Hours of sessions in normal demand periods
   */
  normalDemandSessionHours: number;

  /**
   * Occupancy rate during normal demand periods (0-100)
   */
  normalDemandOccupancyRate: number;

  /**
   * Sessions per hour during normal demand periods
   */
  normalDemandSessionsPerHour: number;

  /**
   * When this occupancy record was created
   */
  createdAt: Date;

  /**
   * When this occupancy record was last updated
   */
  updatedAt: Date;

  /**
   * Last date when data was recalculated
   */
  lastCalculatedAt: Date;
}
